roles/sp/tasks/main.yml
roles/sp/tasks/tng-sdk-pkg.yml

Signed-off-by: peusterm <manuel.peuster@uni-paderborn.de>

Added tng-sdk-package to SP deployment.

---

roles/sp/tasks/api-gtw.yml
roles/sp/tasks/main.yml
roles/sp/tasks/rep.yml

 Adding logging functionalities

---

host_vars/localhost
host_vars/pre-int-vnv-ave.5gtango.eu
roles/vnv/tasks/main.yml
roles/vnv/tasks/tee.yml

@felipevicens please review the TEE component, will integrate with jenkins later
Thanks!

integrate TEE with pre-int-vnv-ave environment #18

---

roles/vnv/tasks/main.yml
roles/vnv/tasks/mongo.yml

Add mongo db to the main of the vnv deployment

Add mongo db to the main of the vnv deployment

---

roles/vnv/tasks/main.yml

Changes:
a4610f3 (Felipe Vicens, 15 seconds ago)
Adding tng-gtk-common to VnV deployment

Adding tng-gtk-common to VnV deployment

---

roles/vnv/tasks/api-gtw.yml
roles/vnv/tasks/lcm.yml
roles/vnv/tasks/main.yml
roles/vnv/tasks/tee.yml

Changes:
4cc63c1 (Felipe Vicens, 33 seconds ago)
No logging endpoint needed
14b5d77 (Felipe Vicens, 71 seconds ago)
Adding tng-api-gtw to VnV deployment

Adding tng-api-gtw to VnV deployment

---

roles/sp/tasks/bss.yml
roles/sp/tasks/main.yml

e5baa0f (Felipe Vicens, 34 seconds ago)
Including gtk-sp in the deployment

Including gtk-sp in the deployment

---

roles/sp/tasks/gtk-sp.yml

Changes:
6e2b843 (Felipe Vicens, 64 seconds ago)
Updating environmnet variables

Updating deployment tng-gtk-sp

---

roles/sp/tasks/gtk-sp.yml

Changes:
14fa0e2 (Felipe Vicens, 18 seconds ago)
Activating postgres migration for tng-gtk-sp

Activating postgres migration for tng-gtk-sp

---

roles/sp/tasks/gtk-sp.yml

Changes:
708711d (Felipe Vicens, 19 seconds ago)
Fix typo tng-gtk-sp playbook

Fix typo tng-gtk-sp playbook

---

roles/sp/tasks/main.yml
roles/vnv/tasks/main.yml
roles/vnv/tasks/portal.yml

Changes:
506a4a9 (Felipe Vicens, 18 seconds ago)
Updating single component deployment

Updating single component deployment

---

roles/sp/tasks/main.yml
roles/sp/tasks/mongo-express.yml

Changes:
a2de419 (Felipe Vicens, 27 seconds ago)
Adding mongo-express for pre-int and int env

Adding mongo-express

---

roles/sp/tasks/k8s-wrapper.yml
roles/sp/tasks/main.yml

Adding kubernetes wrapper deployment

---

environments

Skip deployment in Aveiro due networking issue

---

roles/vnv/tasks/main.yml

Updating platfrom manager vnv deployment

---

roles/sp/tasks/main.yml
roles/vnv/tasks/main.yml

Tracking installations

---

roles/sp/tasks/add-athens-pop1-vim-wim.yml

Signed-off-by: srjuanlu <jdelacruz@cttc.es>

Testing Wtapi - modified pre-int-ath parameters

---

README.md
roles/vnv/tasks/main.yml
roles/vnv/tasks/planner.yml

we have started the implementation of new features of VnV with the new components planner, curator and executor. We had to clean and adapt the code to the new component. We are ready now to add planner in the rest CI/CD infra on 5GTango's components.

Insert planner component

---

roles/vnv/tasks/tng-vnv-planner.yml

(related with https://github.com/sonata-nfv/tng-devops/issues/186,
https://github.com/sonata-nfv/tng-vnv-planner/issues/35)

creating planner's db for the existing gtk_db_user

---

roles/vnv/tasks/tng-vnv-planner.yml

Add planner database in the installation

---

roles/sp/tasks/add-weidmuller-pop1-vim-wim.yaml
roles/sp/tasks/main.yml

Adding weidmuller site

---

roles/vnv/tasks/pgsql.yml
roles/vnv/tasks/tng-vnv-planner.yml

Creating planner database

---

roles/sp/tasks/main.yml
roles/sp/tasks/tng-sdk-portal-backend.yml

For https://github.com/sonata-nfv/tng-portal/pull/448 to work

added SP task to deploy SDK portal backend

---

README.md
vagrant/sp/Vagrantfile
vagrant/vnv/Vagrantfile

Vagrant file for sonata v5.1 installation
